import * as THREE from 'three';
import './style.css';
const root=document.querySelector('#game');
root.innerHTML=['<div id="hud"><div class="topbar"><div><div class="brand">ASHES OF ELDORIA</div><div class="subtitle">THE FALLEN CROWN · CHAPTER I</div></div><div class="panel stats"><div class="statline"><span>VITALITY</span><span id="hpText">100 / 100</span></div><div class="bar"><div id="hp" class="fill" style="width:100%"></div></div><div class="statline"><span>EMBER</span><span id="mpText">60 / 60</span></div><div class="bar"><div id="mana" class="fill" style="width:100%"></div></div><div class="statline"><span>LEVEL 01</span><span id="xpText">0 / 100 XP</span></div></div></div><div class="minimap"><canvas id="map" width="180" height="180"></canvas></div><div class="panel quest"><h3>✦ THE COLD HEARTH</h3><p>Find the source of the ashfall. The old keeper may know what happened to the crown.</p><p id="objective" class="objective">◇ Speak to the Ashen Keeper</p></div><div class="bottomleft">WILDS OF ELDORIA <span style="color:#caa45d">◆</span> THE GREYFRONT</div><div id="hint" class="hint">Explore the ruins. Find the keeper.</div><div id="notice" class="centerNotice">THE ASHEN WILDS</div><div class="controls"><div id="joy" class="joystick"><div id="stick" class="stick"></div></div><div class="actions"><button id="talk" class="act">TALK</button><button id="dodge" class="act">DODGE</button><button id="strike" class="act primary">STRIKE</button><button id="spell" class="act primary">EMBER</button></div></div><div id="dialog" class="panel dialog"><h3 id="dialogTitle">Ashen Keeper</h3><p id="dialogText"></p><button id="dialogNext">CONTINUE</button></div></div><div id="rotate">⟳<br><br>Turn your device sideways to enter Eldoria.</div>'].join('');
const $=id=>document.getElementById(id),scene=new THREE.Scene();scene.background=new THREE.Color(0x9a8d80);scene.fog=new THREE.FogExp2(0x9a8d80,.009);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,500),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;root.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xc9d8df,0x45392b,2));const sun=new THREE.DirectionalLight(0xffd4a0,3.1);sun.position.set(-35,55,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);
const light=new THREE.PointLight(0xff7437,4,20);light.position.set(-12,2,1);scene.add(light);
const M=(c,r=.9,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}),groundMat=M(0x565a48),stone=M(0x77766c),dark=M(0x41444a),bark=M(0x3e332a),leaf=M(0x303e35),gold=M(0xc7a15b,.35,.6),blue=M(0x3d5663),steel=M(0x9ca7aa,.35,.72),red=M(0x28252a),ember=new THREE.MeshBasicMaterial({color:0xff813f});
let seed=71821;const rnd=()=>{seed=seed*16807%2147483647;return(seed-1)/2147483646};
function box(w,h,d,ma,x,y,z){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),ma);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function ball(r,ma,x,y,z,sy=1){const o=new THREE.Mesh(new THREE.SphereGeometry(r,12,10),ma);o.position.set(x,y,z);o.scale.y=sy;o.castShadow=true;scene.add(o);return o}
function cyl(a,b,h,ma,x,y,z,n=8){const o=new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,n),ma);o.position.set(x,y,z);o.castShadow=true;scene.add(o);return o}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(240,240,48,48),groundMat);floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const pa=floor.geometry.attributes.position;for(let i=0;i<pa.count;i++){const x=pa.getX(i),y=pa.getY(i);pa.setZ(i,(Math.sin(x*.12)*Math.cos(y*.1)+Math.sin(y*.23+x*.05)*.35)*.65)}floor.geometry.computeVertexNormals();
function tree(x,z,s=1){cyl(.24*s,.36*s,2.5*s,bark,x,1.25*s,z,7);for(let i=0;i<3;i++){const c=new THREE.Mesh(new THREE.ConeGeometry((1.35-i*.2)*s,2.2*s,7),leaf);c.position.set(x,(2.1+i*.72)*s,z);c.rotation.y=rnd()*3;c.castShadow=true;scene.add(c)}}
for(let i=0;i<125;i++){let x=(rnd()-.5)*210,z=(rnd()-.5)*210;if(Math.hypot(x,z)<16)continue;if(i<100)tree(x,z,.65+rnd()*.9);else{const o=ball(.4+rnd()*1.4,i%2?stone:dark,x,.2,z,.6+rnd());o.rotation.set(rnd(),rnd(),rnd())}}
for(let i=0;i<24;i++){const z=17+i*2.4;const p=box(3.6,.18,2.1,i%3?stone:dark,0,.05,z);p.rotation.y=(rnd()-.5)*.14}
for(const side of [-1,1])for(let i=0;i<5;i++){const x=side*(7.2+(i%2)*.5),z=31+i*2.4;box(1.2,4.8,1.2,stone,x,2.4,z);box(1.55,.4,1.55,dark,x,4.9,z)}
for(let i=0;i<11;i++){const a=i/11*Math.PI*2,x=Math.cos(a)*8,z=42+Math.sin(a)*8,h=2.5+rnd()*3.5;box(1.2,h,1.2,stone,x,h/2,z).rotation.y=rnd()}
box(3.5,1.2,2.8,dark,0,.6,42);box(1.3,.25,1.3,gold,0,1.4,42);const shrineLight=new THREE.PointLight(0xffa54e,2,12);shrineLight.position.set(0,2,42);scene.add(shrineLight);
for(let i=0;i<18;i++){const a=rnd()*Math.PI*2,r=1+rnd()*3,o=ball(.04+rnd()*.07,ember,Math.cos(a)*r,1+rnd()*2,42+Math.sin(a)*r);o.userData.seed=rnd()*8}
function house(x,z){box(4,2.8,3.6,M(0x5a4030),x,1.4,z);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.25,2.2,4),M(0x36373b));roof.position.set(x,3.8,z);roof.rotation.y=Math.PI/4;roof.castShadow=true;scene.add(roof);box(.9,1.6,.12,dark,x,0.8,z-1.86);box(.55,.65,.15,gold,x+1.1,1.8,z-1.88)}
house(-12,5);house(-18,10);house(-14,15);ball(.38,ember,-12,.45,1,.75);const flame=new THREE.Mesh(new THREE.ConeGeometry(.4,1.2,7),new THREE.MeshBasicMaterial({color:0xffb44d}));flame.position.set(-12,1,1);scene.add(flame);
const player=new THREE.Group();scene.add(player);player.position.set(0,0,4);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.9,4,8),blue);torso.position.y=1.45;torso.castShadow=true;player.add(torso);player.add(ball(.34,M(0xb8a18a),0,2.35,0));const helmet=new THREE.Mesh(new THREE.SphereGeometry(.38,8,7,0,Math.PI*2,0,Math.PI*.58),steel);helmet.position.y=2.43;player.add(helmet);const cape=box(.78,1.05,.12,M(0x4b252a),0,1.25,.48);scene.remove(cape);player.add(cape);cape.position.set(0,1.25,.48);
const armL=box(.2,.75,.22,blue,-.58,1.4,0),armR=box(.2,.75,.22,blue,.58,1.4,0);scene.remove(armL,armR);player.add(armL,armR);armL.position.set(-.58,1.4,0);armR.position.set(.58,1.4,0);
const sword=new THREE.Group(),blade=new THREE.Mesh(new THREE.BoxGeometry(.12,1.2,.08),steel);blade.position.y=.65;sword.add(blade);const guard=new THREE.Mesh(new THREE.BoxGeometry(.45,.1,.13),gold);guard.position.y=.18;sword.add(guard);sword.add(new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.32,6),bark));sword.position.set(.65,1.15,-.15);sword.rotation.z=-.35;player.add(sword);
function humanoid(x,z,keeper=false){const g=new THREE.Group();g.position.set(x,0,z);scene.add(g);const body=new THREE.Mesh(new THREE.CapsuleGeometry(keeper?.42:.48,keeper?.85:1,4,8),keeper?M(0x74674d):red);body.position.y=1.3;body.castShadow=true;g.add(body);g.add(ball(.31,keeper?M(0xc5ad8b):M(0x5c4946),0,2.15,0));const hood=new THREE.Mesh(new THREE.ConeGeometry(.42,.75,7),keeper?M(0x3d4742):M(0x211e24));hood.position.y=2.45;g.add(hood);if(!keeper){const eyes=new THREE.MeshBasicMaterial({color:0xff3b24});g.add(ball(.055,eyes,-.12,2.16,-.27),ball(.055,eyes,.12,2.16,-.27));g.add(box(.13,1.1,.12,M(0x6a594a),.52,1.1,-.05))}else{g.add(cyl(.06,.08,2.1,bark,.52,1.1,0,6),ball(.18,ember,.52,2.2,0))}return g}
const keeper=humanoid(-9,2,true),enemies=[];for(let i=0;i<7;i++){const a=i/7*Math.PI*2,r=18+rnd()*18;enemies.push({mesh:humanoid(Math.cos(a)*r,Math.sin(a)*r+20),hp:3,attack:0,hit:0,alive:true})}
const pickups=[];for(let i=0;i<6;i++){const a=i*2.4,r=7+(i%3)*3,m=ball(.25,gold,Math.cos(a)*r,.65,15+Math.sin(a)*r);m.userData.baseY=.65;pickups.push({mesh:m,got:false})}
const s={hp:100,mana:60,xp:0,level:1,quest:0,kills:0,dialog:false,dead:false,attack:0,spell:0,dodge:0,invuln:0};let yaw=0,pitch=.22,joy={x:0,y:0},joyActive=false,noticeTime=0;
function notice(t){$('notice').textContent=t;$('notice').style.opacity='1';noticeTime=2.4;$('hint').textContent=t}
function say(title,text){$('dialogTitle').textContent=title;$('dialogText').textContent=text;$('dialog').style.display='block';s.dialog=true}
function close(){ $('dialog').style.display='none';s.dialog=false }
$('dialogNext').onclick=()=>{if(s.quest===0){s.quest=1;$('objective').textContent='◇ Defeat 3 ash-wraiths (0/3)';say('Ashen Keeper','The shrine is waking. Three wraiths guard the road. Break their ash-bound forms, then return to me.')}else if(s.quest===1&&s.kills>=3){s.quest=2;$('objective').textContent='◇ Reach the Crown Shrine';say('Ashen Keeper','You have weakened the curse. Go to the shrine beyond the broken road. The fallen crown still remembers its king.')}else close()};
function interact(){if(s.dialog){close();return}if(player.position.distanceTo(keeper.position)<4){if(s.quest===0)say('Ashen Keeper','You came through the ashfall alive. The crown-shrine has gone dark, and the dead walk again. Will you help me learn why?');else if(s.quest===1&&s.kills<3)say('Ashen Keeper','The wraiths still haunt the wilds. Find them beyond the village and strike when they draw near.');else say('Ashen Keeper','The shrine has heard your footsteps. Follow the ember-light.');return}if(player.position.distanceTo(new THREE.Vector3(0,0,42))<5){if(s.quest<2)say('Crown Shrine','The stone is cold. The keeper may know how to awaken it.');else{s.quest=3;$('objective').textContent='✦ Chapter complete — the crown stirs';say('THE FALLEN CROWN','A pulse of ancient fire travels through the stone. Far beneath Eldoria, something answers. Chapter I complete.');notice('CHAPTER I COMPLETE')}return}const p=pickups.find(p=>!p.got&&player.position.distanceTo(p.mesh.position)<2.4);if(p){p.got=true;scene.remove(p.mesh);s.mana=Math.min(60,s.mana+15);s.xp+=10;notice('EMBER SHARD +10 XP');hudUpdate();return}notice('Nothing to interact with nearby')}
function hudUpdate(){$('hp').style.width=s.hp+'%';$('hpText').textContent=Math.ceil(s.hp)+' / 100';$('mana').style.width=(s.mana/60*100)+'%';$('mpText').textContent=Math.ceil(s.mana)+' / 60';$('xpText').textContent=s.xp+' / 100 XP'}
function nearest(max=4.5){let b=null,d0=max;for(const e of enemies){if(!e.alive)continue;const d=player.position.distanceTo(e.mesh.position);if(d<d0){d0=d;b=e}}return b}
function hit(e,n){e.hp-=n;e.hit=.25;e.mesh.scale.set(1.15,.9,1.15);if(e.hp<=0){e.alive=false;scene.remove(e.mesh);s.kills++;s.xp+=25;s.mana=Math.min(60,s.mana+4);if(s.quest===1)$('objective').textContent='◇ Defeat 3 ash-wraiths ('+Math.min(3,s.kills)+'/3)';notice('WRAITH BANISHED +25 XP');if(s.xp>=100){s.level++;s.xp-=100;notice('LEVEL UP · '+s.level)}hudUpdate()}else notice('HIT · '+e.hp+' VITALITY LEFT')}
function strike(){if(s.dialog||s.dead)return;s.attack=.36;const e=nearest(4.2);if(e){hit(e,1);e.mesh.position.add(e.mesh.position.clone().sub(player.position).setY(0).normalize().multiplyScalar(.75))}else notice('Your blade cuts through empty air')}
function spell(){if(s.dialog||s.dead)return;if(s.mana<15){notice('NOT ENOUGH EMBER');return}s.mana-=15;s.spell=.5;hudUpdate();const e=nearest(12),orb=ball(.3,new THREE.MeshBasicMaterial({color:0xff9a4c}),player.position.x,player.position.y+1.5,player.position.z-1),start=orb.position.clone();if(e){const end=e.mesh.position.clone().add(new THREE.Vector3(0,1.4,0)),t0=performance.now();const fly=()=>{const t=Math.min(1,(performance.now()-t0)/240);orb.position.lerpVectors(start,end,t);if(t<1)requestAnimationFrame(fly);else{scene.remove(orb);if(e.alive)hit(e,2)}};fly()}else{setTimeout(()=>scene.remove(orb),400);notice('EMBER FLARE')}}
function dodge(){if(s.dialog||s.dead)return;s.dodge=.3;s.invuln=.45;player.position.add(new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)).multiplyScalar(2.6));notice('DODGE')}
$('talk').onclick=interact;$('strike').onclick=strike;$('spell').onclick=spell;$('dodge').onclick=dodge;
const joyEl=$('joy'),stick=$('stick');function joyMove(e){const r=joyEl.getBoundingClientRect(),dx0=(e.clientX-r.left-r.width/2)/(r.width*.36),dy0=(e.clientY-r.top-r.height/2)/(r.height*.36),l=Math.hypot(dx0,dy0),k=Math.max(1,l);joy={x:dx0/k,y:dy0/k};stick.style.left=(50+joy.x*34)+'%';stick.style.top=(50+joy.y*34)+'%'}joyEl.onpointerdown=e=>{joyActive=true;joyEl.setPointerCapture(e.pointerId);joyMove(e)};joyEl.onpointermove=e=>{if(joyActive)joyMove(e)};function resetJoy(){joyActive=false;joy={x:0,y:0};stick.style.left='50%';stick.style.top='50%'}joyEl.onpointerup=resetJoy;joyEl.onpointercancel=resetJoy;
let drag=false,lx=0,ly=0;renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY});window.addEventListener('pointerup',()=>drag=false);window.addEventListener('pointermove',e=>{if(drag){yaw-=(e.clientX-lx)*.005;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-ly)*.003,-.05,.75);lx=e.clientX;ly=e.clientY}});
window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e')interact();if(e.key===' '||e.key.toLowerCase()==='j')strike();if(e.key.toLowerCase()==='k')spell();if(e.key==='Shift')dodge();if(['w','ArrowUp'].includes(e.key))joy.y=-1;if(['s','ArrowDown'].includes(e.key))joy.y=1;if(['a','ArrowLeft'].includes(e.key))joy.x=-1;if(['d','ArrowRight'].includes(e.key))joy.x=1});window.addEventListener('keyup',e=>{if('wasdArrowUpArrowDownArrowLeftArrowRight'.includes(e.key))joy={x:0,y:0}});
const ctx=$('map').getContext('2d');function drawMap(){ctx.clearRect(0,0,180,180);ctx.fillStyle='#1b2826';ctx.fillRect(0,0,180,180);ctx.strokeStyle='#88785b';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(90,80);ctx.lineTo(90,145);ctx.stroke();ctx.fillStyle='#d6b26d';ctx.beginPath();ctx.arc(90+player.position.x*.8,90+player.position.z*.8,4,0,7);ctx.fill();ctx.fillStyle='#ff6143';for(const e of enemies)if(e.alive){ctx.beginPath();ctx.arc(90+e.mesh.position.x*.8,90+e.mesh.position.z*.8,2.5,0,7);ctx.fill()}ctx.fillStyle='#8ad9ff';ctx.fillRect(82,123,5,5)}
const clock=new THREE.Clock(),target=new THREE.Vector3();function animate(now){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);if(noticeTime>0&& (noticeTime-=dt)<=0)$('notice').style.opacity='0';if(!s.dialog&&!s.dead){const move=new THREE.Vector3(-Math.sin(yaw)*(-joy.y)+Math.cos(yaw)*joy.x,0,-Math.cos(yaw)*(-joy.y)-Math.sin(yaw)*joy.x);if(move.lengthSq()>0){move.normalize();player.position.addScaledVector(move,5.3*dt);player.position.x=THREE.MathUtils.clamp(player.position.x,-100,100);player.position.z=THREE.MathUtils.clamp(player.position.z,-100,100);player.rotation.y=Math.atan2(-move.x,-move.z);armL.rotation.x=Math.sin(now*.015)*.25;armR.rotation.x=-Math.sin(now*.015)*.25}for(const e of enemies){if(!e.alive)continue;const d=player.position.clone().sub(e.mesh.position),dist=d.length();e.attack-=dt;if(dist<18&&dist>1.7){d.y=0;d.normalize();e.mesh.position.addScaledVector(d,dt*(dist<7?1.7:1.15));e.mesh.rotation.y=Math.atan2(-d.x,-d.z)}if(dist<2.1&&e.attack<=0&&s.invuln<=0){e.attack=1.35;s.hp=Math.max(0,s.hp-8);hudUpdate();notice('ASH WRAITH STRIKES');if(!s.hp){s.dead=true;say('FALLEN IN THE ASH','The wilds claim another wanderer. Refresh to rise again.')}}if(e.hit>0&&(e.hit-=dt)<=0)e.mesh.scale.set(1,1,1)}}s.invuln=Math.max(0,s.invuln-dt);if(s.attack>0){s.attack-=dt;sword.rotation.z=-.35-Math.sin((.36-s.attack)/.36*Math.PI)*1.8}else sword.rotation.z=THREE.MathUtils.damp(sword.rotation.z,-.35,12,dt);for(const p of pickups)if(!p.got){p.mesh.rotation.y+=dt;p.mesh.position.y=p.mesh.userData.baseY+Math.sin(now*.002+p.mesh.position.x)*.16}for(const o of scene.children)if(o.userData.seed!==undefined)o.position.y=1.5+Math.sin(now*.0015+o.userData.seed)*.4;light.intensity=3.5+Math.sin(now*.018)*.8;shrineLight.intensity=2+Math.sin(now*.002)*.5;target.set(player.position.x,player.position.y+1.3,player.position.z);camera.position.lerp(target.clone().add(new THREE.Vector3(Math.sin(yaw)*9,3.2+pitch*5,Math.cos(yaw)*9)),1-Math.pow(.001,dt));camera.lookAt(target);drawMap();renderer.render(scene,camera)}
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('rotate').style.display=innerHeight>innerWidth?'flex':'none'});$('rotate').style.display=innerHeight>innerWidth?'flex':'none';try{const save=JSON.parse(localStorage.getItem('eldoria-save')||'null');if(save){s.quest=save.quest||0;s.kills=save.kills||0;s.xp=save.xp||0;s.level=save.level||1;if(s.quest===1)$('objective').textContent='◇ Defeat 3 ash-wraiths ('+Math.min(3,s.kills)+'/3)'}}catch{}setInterval(()=>{try{localStorage.setItem('eldoria-save',JSON.stringify({quest:s.quest,kills:s.kills,xp:s.xp,level:s.level}))}catch{}},4000);notice('THE ASHEN WILDS');requestAnimationFrame(animate);
